### ISSUE TITLE
When is the code for unsupervised multi-domain image-to-image translation being released?

### ISSUE THREAD

**Issue by gigadeplex** [Ha0Tang/AsymmetricGAN#1]
This is not a implementation of the actual paper "DualGeneratorGenerativeAdversarialNetworksfor Multi-DomainImage-to-ImageTranslation" but instead "GestureGANforHandGesture-to-GestureTranslation intheWild".

**Comment by Ha0Tang** [comment]
@gigadeplex the code has been released.
